var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var LevelInfo_IC = (function () {
    function LevelInfo_IC() {
    }
    // public static xml = 
    LevelInfo_IC.xml = '<levelCfg>'
        + ' <lv id=\'1\'><lvEft><styleNum>1</styleNum></lvEft></lv>'
        + ' <lv id=\'2\'><lvEft><styleNum>2</styleNum></lvEft></lv>'
        + ' <lv id=\'3\'><lvEft><styleNum>3</styleNum></lvEft></lv>'
        + ' <lv id=\'4\'><lvEft><styleNum>4</styleNum></lvEft></lv>'
        + ' <lv id=\'5\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'6\'><lvEft><styleNum>5</styleNum></lvEft></lv>'
        + ' <lv id=\'7\'><lvEft><styleNum>6</styleNum></lvEft></lv>'
        + ' <lv id=\'8\'><lvEft><styleNum>7</styleNum></lvEft></lv>'
        + ' <lv id=\'9\'><lvEft><styleNum>8</styleNum></lvEft></lv>'
        + ' <lv id=\'10\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'11\'><lvEft><styleNum>9</styleNum></lvEft></lv>'
        + ' <lv id=\'12\'><lvEft><styleNum>10</styleNum></lvEft></lv>'
        + ' <lv id=\'13\'><lvEft><styleNum>11</styleNum></lvEft></lv>'
        + ' <lv id=\'14\'><lvEft><styleNum>12</styleNum></lvEft></lv>'
        + ' <lv id=\'15\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'16\'><lvEft><styleNum>13</styleNum></lvEft></lv>'
        + ' <lv id=\'17\'><lvEft><styleNum>14</styleNum></lvEft></lv>'
        + ' <lv id=\'18\'><lvEft><styleNum>15</styleNum></lvEft></lv>'
        + ' <lv id=\'19\'><lvEft><styleNum>16</styleNum></lvEft></lv>'
        + ' <lv id=\'20\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'21\'><lvEft><styleNum>17</styleNum></lvEft></lv>'
        + ' <lv id=\'22\'><lvEft><styleNum>18</styleNum></lvEft></lv>'
        + ' <lv id=\'23\'><lvEft><styleNum>19</styleNum></lvEft></lv>'
        + ' <lv id=\'24\'><lvEft><styleNum>20</styleNum></lvEft></lv>'
        + ' <lv id=\'25\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'26\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'27\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravLeft</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'28\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravRight</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'29\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravUp</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'30\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'31\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravHorCent</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'32\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravVerCent</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'33\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravHorEdge</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'34\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravVerEdge</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'35\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'36\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveDown</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'37\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveUp</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'38\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveLeft</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'39\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveRight</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'40\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'41\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '   <gEft>gravLeft</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'42\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '   <gEft>gravRight</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'43\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravUp</gEft>'
        + '   <gEft>gravLeft</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'44\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravUp</gEft>'
        + '   <gEft>gravRight</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'45\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'46\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravLeft</gEft>'
        + '   <gEft>gravDown</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'47\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravLeft</gEft>'
        + '   <gEft>gravUp</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'48\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravRight</gEft>'
        + '   <gEft>gravDown</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'49\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravRight</gEft>'
        + '   <gEft>gravUp</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'50\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'51\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravHorCent</gEft>'
        + '   <gEft>gravVerCent</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'52\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravVerCent</gEft>'
        + '   <gEft>gravHorCent</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'53\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravHorEdge</gEft>'
        + '   <gEft>gravVerEdge</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'54\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravVerEdge</gEft>'
        + '   <gEft>gravHorEdge</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'55\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'56\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveDown</gEft>'
        + '   <gEft>moveLeft</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'57\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveDown</gEft>'
        + '   <gEft>moveRight</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'58\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveUp</gEft>'
        + '   <gEft>moveLeft</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'59\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveUp</gEft>'
        + '   <gEft>moveRight</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'60\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'61\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '   <gEft>moveLeft</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'62\'>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '   <gEft>moveRight</gEft>'
        + '  </lvEft>'
        + ' </lv>'
        + ' <lv id=\'63\'>'
        + '  <lvEft><styleNum>1</styleNum></lvEft>'
        + '  <lvEft><styleNum>11</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'64\'>'
        + '  <lvEft><styleNum>2</styleNum></lvEft>'
        + '  <lvEft><styleNum>12</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'65\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'66\'>'
        + '  <lvEft><styleNum>3</styleNum></lvEft>'
        + '  <lvEft><styleNum>13</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'67\'>'
        + '  <lvEft><styleNum>4</styleNum></lvEft>'
        + '  <lvEft><styleNum>14</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'68\'>'
        + '  <lvEft><styleNum>5</styleNum></lvEft>'
        + '  <lvEft><styleNum>15</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'69\'>'
        + '  <lvEft><styleNum>6</styleNum></lvEft>'
        + '  <lvEft><styleNum>16</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'70\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'71\'>'
        + '  <lvEft><styleNum>7</styleNum></lvEft>'
        + '  <lvEft><styleNum>17</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'72\'>'
        + '  <lvEft><styleNum>8</styleNum></lvEft>'
        + '  <lvEft><styleNum>18</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'73\'>'
        + '  <lvEft><styleNum>9</styleNum></lvEft>'
        + '  <lvEft><styleNum>19</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'74\'>'
        + '  <lvEft><styleNum>10</styleNum></lvEft>'
        + '  <lvEft><styleNum>20</styleNum></lvEft>'
        + '  </lv>'
        + ' <lv id=\'75\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'76\'>'
        + '  <lvEft><styleNum>1</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'77\'>'
        + '  <lvEft><styleNum>2</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravLeft</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'78\'>'
        + '  <lvEft><styleNum>3</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravRight</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'79\'>'
        + '  <lvEft><styleNum>4</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravUp</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'80\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'81\'>'
        + '  <lvEft><styleNum>5</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravHorCent</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'82\'>'
        + '  <lvEft><styleNum>6</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravVerCent</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'83\'>'
        + '  <lvEft><styleNum>7</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravHorEdge</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'84\'>'
        + '  <lvEft><styleNum>8</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravVerEdge</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'85\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'86\'>'
        + '  <lvEft><styleNum>9</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveDown</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'87\'>'
        + '  <lvEft><styleNum>10</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveUp</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'88\'>'
        + '  <lvEft><styleNum>11</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveLeft</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'89\'>'
        + '  <lvEft><styleNum>12</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>moveRight</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'90\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'91\'>'
        + '  <lvEft><styleNum>13</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '   <gEft>gravLeft</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'92\'>'
        + '  <lvEft><styleNum>14</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravDown</gEft>'
        + '   <gEft>gravRight</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'93\'>'
        + '  <lvEft><styleNum>15</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravUp</gEft>'
        + '   <gEft>gravLeft</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'94\'>'
        + '  <lvEft><styleNum>16</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravUp</gEft>'
        + '   <gEft>gravRight</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'95\'><lvEft><boss>1</boss></lvEft></lv>'
        + ' <lv id=\'96\'>'
        + '  <lvEft><styleNum>17</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravLeft</gEft>'
        + '   <gEft>gravDown</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'97\'>'
        + '  <lvEft><styleNum>18</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravLeft</gEft>'
        + '   <gEft>gravUp</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'98\'>'
        + '  <lvEft><styleNum>19</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravRight</gEft>'
        + '   <gEft>gravDown</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'99\'>'
        + '  <lvEft><styleNum>20</styleNum></lvEft>'
        + '  <lvEft><styleNum>0</styleNum>'
        + '   <gEft>gravRight</gEft>'
        + '   <gEft>gravUp</gEft>'
        + '  </lvEft>'
        + '  </lv>'
        + ' <lv id=\'100\'><lvEft><boss>1</boss></lvEft></lv>'
        + '</levelCfg>';
    return LevelInfo_IC;
}());
__reflect(LevelInfo_IC.prototype, "LevelInfo_IC");
//# sourceMappingURL=LevelInfo_IC.js.map