class Moriya_Combo extends Combo_listener
{
    constructor(r)
    {
        super();
        this.role = r;
        this.init();
    } // End of the function
    public init()
    {
        this.combo1 = new Object();
        this.combo1.sk_yueying_a1 = {punch_l: "sk_yueying_a2", sk_yueying_a1: "sk_yueying_a2"};
        this.combo1.sk_yueying_a2 = {punch_l: "sk_yueying_a3", sk_yueying_a1: "sk_yueying_a3"};
        this.combo1.sk_yueying_c1 = {punch: "sk_yueying_c2", sk_yueying_c1: "sk_yueying_c2"};
        this.combo1.sk_yueying_c2 = {punch: "sk_yueying_c3", sk_yueying_c1: "sk_yueying_c3"};
        this.combo1.sk_yueying_c3 = {punch: "sk_yueying_c4", sk_yueying_c1: "sk_yueying_c4"};
        this.combo1.sk_xinyue = {sk_xinyue2: "sk_xinyue2", punch3: "sk_xinyue2"};
        this.combo2 = new Object();
        this.combo2.punch = 11;
        this.combo2.punch2 = 7;
        this.combo2.punch3 = 11;
        this.combo2.kick = 11;
        this.combo2.squatPunch = 8;
        this.combo2.heavyHit = 11;
        this.combo2.sk_yueying_a1 = 9;
        this.combo2.sk_yueying_a2 = 15;
        this.combo2.sk_yueying_c1 = 14;
        this.combo2.sk_yueying_c2 = 9;
        this.combo2.sk_yueying_c3 = 10;
        this.combo2.sk_xinyue = 15;
        this.combo2.sk_xinyue2 = 15;
        this.combo2.sk_buyue3 = 10;
        this.combo2.sk_buyue2 = 10;
        this.combo2.sk_buyue1 = 10;
        this.combo2.sk_long_u = 16;
        this.combo2.sk_long_m = 15;
        this.combo2.sk_long_d = 15;
        this.combo2.sk_buyue1 = 9;
        this.combo2.sk_buyue2 = 8;
        this.combo2.sk_buyue3 = 8;
        this.combo2.sk_yuedu1 = 31;
        this.combo2.sk_yuedu2 = 32;
        this.combo2.sk_s1 = 78;
        this.combo2.sk_s2 = 90;
        this.combo2.sk_feng = 10;
        this.combo2.sk_xue = 15;
        this.skill_over = new Object();
        this.skill_over.punch = 15;
        this.skill_over.punch2 = 12;
        this.skill_over.punch3 = 13;
        this.skill_over.kick = 15;
        this.skill_over.squatPunch = 14;
        this.skill_over.squatKick = 11;
        this.skill_over.heavyHit = 15;
        this.skill_over.sk_yueying_a1 = 9;
        this.skill_over.sk_yueying_a2 = 15;
        this.skill_over.sk_yueying_c1 = 15;
        this.skill_over.sk_yueying_c2 = 15;
        this.skill_over.sk_yueying_c3 = 12;
        this.skill_over.sk_yueying_c4 = 13;
        this.skill_over.sk_xinyue = 15;
        this.skill_over.sk_xinyue2 = 20;
        this.skill_over.sk_long_u = 19;
        this.skill_over.sk_long_m = 18;
        this.skill_over.sk_long_d = 17;
        this.skill_over.sk_buyue1 = 17;
        this.skill_over.sk_buyue2 = 15;
        this.skill_over.sk_buyue3 = 16;
        this.skill_over.sk_buyue1 = 13;
        this.skill_over.sk_yuedu1 = 14;
        this.skill_over.sk_s1 = 78;
        this.skill_over.sk_s2 = 90;
        this.skill_over.sk_s3 = 56;
        this.skill_over.sk_s4 = 13;
        this.skill_over.sk_feng = 35;
        this.skill_over.sk_feng_s = 45;
        this.skill_over.sk_xue = 35;
        this.skill_over.sk_xue_s = 60;
        this.skill_over.sk_s_q1 = 15;
        this.skill_over.sk_s_q2 = 100;
        this.beCancled = new Object();
        this.beCancled.punch = 1;
        this.beCancled.punch2 = 1;
        this.beCancled.punch_s1 = 1;
        this.beCancled.punch_l = 1;
        this.beCancled.kick = 1;
        this.beCancled.kick2 = 1;
        this.beCancled.kick_s1 = 1;
        this.beCancled.kick_s2 = 1;
        this.beCancled.kick_l = 1;
        this.beCancled.squatPunch = 1;
        this.beCancled.squatPunch_l = 1;
        this.beCancled.squatKick_l = 1;
        this.beCancled.sk_buyue1 = 1;
        this.beCancled.sk_buyue2 = 1;
        this.beCancled.sk_buyue3 = 1;
        this.notTOcancle = new Object();
        this.notTOcancle.punch = 1;
        this.notTOcancle.punch2 = 1;
        this.notTOcancle.punch_l = 1;
        this.notTOcancle.kick = 1;
        this.notTOcancle.kick_l = 1;
        this.notTOcancle.squatPunch = 1;
        this.notTOcancle.squatPunch_l = 1;
        this.notTOcancle.squatKick_l = 1;
        this.notTOcancle.squatKick = 1;
        this.notTOcancle.pitch = 1;
        this.s_cancle = new Object();
    } // End of the function
} // End of Class
