class Mai_Combo extends role_corn.Combo_listener
{
    var role, combo1, combo2, skill_over, beCancled, notTOcancle, s_cancle;
    function Mai_Combo(r)
    {
        super();
        role = r;
        this.init();
    } // End of the function
    function init()
    {
        combo1 = new Object();
        combo1.sk_luan1 = {punch: "sk_luan2", punch_l: "sk_luan2"};
        combo1.sk_luan2 = {punch: "sk_luan3", punch_l: "sk_luan3"};
        combo1.sk_luan3 = {punch: "sk_luan4", punch_l: "sk_luan4"};
        combo1.sk_luan4 = {punch: "sk_luan5", punch_l: "sk_luan5"};
        combo2 = new Object();
        combo2.punch = 8;
        combo2.punch2 = 6;
        combo2.kick_s1 = 10;
        combo2.punch_s = 73;
        combo2.kick = 12;
        combo2.kick2 = 6;
        combo2.kick_s2 = 13;
        combo2.squatPunch = 8;
        combo2.punch_l = 5;
        combo2.squatPunch_l = 6;
        combo2.kick_l = 7;
        combo2.squatKick_l = 5;
        combo2.heavyHit = 14;
        combo2.sk_renfeng = 7;
        combo2.sk_huaxing = 7;
        combo2.sk_qianniao = 13;
        combo2.sk_beike = 15;
        combo2.sk_huadieshan = 12;
        combo2.sk_bailu = 26;
        combo2.sk_longyanwu = 15;
        combo2.sk_bailu2 = 17;
        combo2.sk_longyanwu2 = 15;
        combo2.sk_luan1 = 9;
        combo2.sk_luan2 = 9;
        combo2.sk_luan3 = 9;
        combo2.sk_luan4 = 6;
        combo2.sk_luan5 = 30;
        combo2.sk_s_shuiniao = 21;
        combo2.sk_s_renfeng = 27;
        combo2.sk_s_hualan = 40;
        combo2.sk_s_fenghuang = 67;
        skill_over = new Object();
        skill_over.punch = 15;
        skill_over.punch2 = 17;
        skill_over.kick_s1 = 14;
        skill_over.kick = 13;
        skill_over.kick2 = 11;
        skill_over.squatPunch = 12;
        skill_over.squatKick = 10;
        skill_over.heavyHit = 15;
        skill_over.sk_huaxing = 15;
        skill_over.sk_renfeng = 20;
        skill_over.sk_qianniao = 19;
        skill_over.sk_bailu = 26;
        skill_over.sk_longyanwu = 18;
        skill_over.sk_bailu = 26;
        skill_over.sk_longyanwu = 15;
        skill_over.sk_s_heti = 28;
        skill_over.sk_s_qianzai1 = 21;
        skill_over.sk_s_shuiniao = 30;
        skill_over.sk_s_shuiniao_s = 32;
        skill_over.sk_s_renfeng = 35;
        skill_over.sk_s_renfeng_s = 30;
        skill_over.sk_s_hualan = 40;
        skill_over.sk_s_hualan_s = 50;
        skill_over.sk_s_fenghuang = 67;
        beCancled = new Object();
        beCancled.punch = 1;
        beCancled.punch2 = 1;
        beCancled.kick_s1 = 1;
        beCancled.punch_l = 1;
        beCancled.kick = 1;
        beCancled.kick2 = 1;
        beCancled.kick_s1 = 1;
        beCancled.kick_s2 = 1;
        beCancled.kick_l = 1;
        beCancled.squatPunch = 1;
        beCancled.squatPunch_l = 1;
        beCancled.squatKick_l = 1;
        notTOcancle = new Object();
        notTOcancle.punch = 1;
        notTOcancle.punch2 = 1;
        notTOcancle.punch_l = 1;
        notTOcancle.kick = 1;
        notTOcancle.kick_l = 1;
        notTOcancle.squatPunch = 1;
        notTOcancle.squatPunch_l = 1;
        notTOcancle.squatKick_l = 1;
        notTOcancle.squatKick = 1;
        notTOcancle.pitch = 1;
        s_cancle = new Object();
        s_cancle.punch_l = {kick_l: 1, squatPunch_l: 1, squatKick_l: 1, punch: 1, kick: 1};
        s_cancle.kick_l = {punch: 1, kick: 1};
        s_cancle.squatPunch_l = {punch_l: 1, kick_l: 1, squatKick_l: 1, punch: 1, kick: 1};
        s_cancle.squatKick_l = {punch_l: 1, kick_l: 1, punch: 1, kick: 1};
        s_cancle.jump_f = {sk_feishu: 1};
    } // End of the function
} // End of Class
