class Moriya_Combo extends role_corn.Combo_listener
{
    var role, combo1, combo2, skill_over, beCancled, notTOcancle, s_cancle;
    function Moriya_Combo(r)
    {
        super();
        role = r;
        this.init();
    } // End of the function
    function init()
    {
        combo1 = new Object();
        combo1.sk_yueying_a1 = {punch_l: "sk_yueying_a2", sk_yueying_a1: "sk_yueying_a2"};
        combo1.sk_yueying_a2 = {punch_l: "sk_yueying_a3", sk_yueying_a1: "sk_yueying_a3"};
        combo1.sk_yueying_c1 = {punch: "sk_yueying_c2", sk_yueying_c1: "sk_yueying_c2"};
        combo1.sk_yueying_c2 = {punch: "sk_yueying_c3", sk_yueying_c1: "sk_yueying_c3"};
        combo1.sk_yueying_c3 = {punch: "sk_yueying_c4", sk_yueying_c1: "sk_yueying_c4"};
        combo1.sk_xinyue = {sk_xinyue2: "sk_xinyue2", punch3: "sk_xinyue2"};
        combo2 = new Object();
        combo2.punch = 11;
        combo2.punch2 = 7;
        combo2.punch3 = 11;
        combo2.kick = 11;
        combo2.squatPunch = 8;
        combo2.heavyHit = 11;
        combo2.sk_yueying_a1 = 9;
        combo2.sk_yueying_a2 = 15;
        combo2.sk_yueying_c1 = 14;
        combo2.sk_yueying_c2 = 9;
        combo2.sk_yueying_c3 = 10;
        combo2.sk_xinyue = 15;
        combo2.sk_xinyue2 = 15;
        combo2.sk_buyue3 = 10;
        combo2.sk_buyue2 = 10;
        combo2.sk_buyue1 = 10;
        combo2.sk_long_u = 16;
        combo2.sk_long_m = 15;
        combo2.sk_long_d = 15;
        combo2.sk_buyue1 = 9;
        combo2.sk_buyue2 = 8;
        combo2.sk_buyue3 = 8;
        combo2.sk_yuedu1 = 31;
        combo2.sk_yuedu2 = 32;
        combo2.sk_s1 = 78;
        combo2.sk_s2 = 90;
        combo2.sk_feng = 10;
        combo2.sk_xue = 15;
        skill_over = new Object();
        skill_over.punch = 15;
        skill_over.punch2 = 12;
        skill_over.punch3 = 13;
        skill_over.kick = 15;
        skill_over.squatPunch = 14;
        skill_over.squatKick = 11;
        skill_over.heavyHit = 15;
        skill_over.sk_yueying_a1 = 9;
        skill_over.sk_yueying_a2 = 15;
        skill_over.sk_yueying_c1 = 15;
        skill_over.sk_yueying_c2 = 15;
        skill_over.sk_yueying_c3 = 12;
        skill_over.sk_yueying_c4 = 13;
        skill_over.sk_xinyue = 15;
        skill_over.sk_xinyue2 = 20;
        skill_over.sk_long_u = 19;
        skill_over.sk_long_m = 18;
        skill_over.sk_long_d = 17;
        skill_over.sk_buyue1 = 17;
        skill_over.sk_buyue2 = 15;
        skill_over.sk_buyue3 = 16;
        skill_over.sk_buyue1 = 13;
        skill_over.sk_yuedu1 = 14;
        skill_over.sk_s1 = 78;
        skill_over.sk_s2 = 90;
        skill_over.sk_s3 = 56;
        skill_over.sk_s4 = 13;
        skill_over.sk_feng = 35;
        skill_over.sk_feng_s = 45;
        skill_over.sk_xue = 35;
        skill_over.sk_xue_s = 60;
        skill_over.sk_s_q1 = 15;
        skill_over.sk_s_q2 = 100;
        beCancled = new Object();
        beCancled.punch = 1;
        beCancled.punch2 = 1;
        beCancled.punch_s1 = 1;
        beCancled.punch_l = 1;
        beCancled.kick = 1;
        beCancled.kick2 = 1;
        beCancled.kick_s1 = 1;
        beCancled.kick_s2 = 1;
        beCancled.kick_l = 1;
        beCancled.squatPunch = 1;
        beCancled.squatPunch_l = 1;
        beCancled.squatKick_l = 1;
        beCancled.sk_buyue1 = 1;
        beCancled.sk_buyue2 = 1;
        beCancled.sk_buyue3 = 1;
        notTOcancle = new Object();
        notTOcancle.punch = 1;
        notTOcancle.punch2 = 1;
        notTOcancle.punch_l = 1;
        notTOcancle.kick = 1;
        notTOcancle.kick_l = 1;
        notTOcancle.squatPunch = 1;
        notTOcancle.squatPunch_l = 1;
        notTOcancle.squatKick_l = 1;
        notTOcancle.squatKick = 1;
        notTOcancle.pitch = 1;
        s_cancle = new Object();
    } // End of the function
} // End of Class
