class Terry_Combo extends role_corn.Combo_listener
{
    var role, combo1, combo2, skill_over, beCancled, notTOcancle, s_cancle;
    function Terry_Combo(r)
    {
        super();
        role = r;
        this.init();
    } // End of the function
    function init()
    {
        combo1 = new Object();
        combo1.df_k1 = {kick: "df_k2", kick_l: "df_k2"};
        combo1.df_k2 = {kick: "df_k3", kick_l: "df_k3"};
        combo1.df_k_EX = {kick: "fdf_kl", kick_l: "fdf_kl"};
        combo2 = new Object();
        skill_over = new Object();
        combo2.punch_l = 3;
        skill_over.punch_l = 5;
        combo2.punch = 7;
        skill_over.punch = 9;
        combo2.punch2 = 8;
        skill_over.punch2 = 12;
        combo2.kick_l = 12;
        skill_over.kick_l = 12;
        combo2.kick = 10;
        skill_over.kick = 14;
        combo2.kick2 = 6;
        skill_over.kick2 = 13;
        combo2.squatPunch = 5;
        skill_over.squatPunch = 12;
        combo2.squatPunch_l = 3;
        skill_over.squatPunch_l = 5;
        combo2.squatKick = 8;
        skill_over.squatKick = 13;
        combo2.squatKick_l = 3;
        skill_over.squatKick_l = 5;
        combo2.heavyHit = 12;
        skill_over.heavyHit = 15;
        combo2.f_p = 9;
        skill_over.f_p = 13;
        combo2.f_p_EX = 8;
        skill_over.f_p_EX = 10;
        combo2.df_p = 4;
        skill_over.df_p = 9;
        combo2.bdf_k = 24;
        skill_over.bdf_k = 30;
        combo2.df_ph = 14;
        skill_over.df_ph = 32;
        combo2.df_pl = 15;
        skill_over.df_pl = 23;
        combo2.df_p_EX = 17;
        skill_over.df_p_EX = 32;
        skill_over.db_k = 18;
        combo2.fdb_p_EX = 16;
        skill_over.fdb_p_EX = 21;
        combo2.db_p = 28;
        skill_over.db_p = 28;
        combo2.fdf_p = 4;
        skill_over.fdf_p = 24;
        combo2.fdf_p_EX = 17;
        skill_over.fdf_p_EX = 29;
        combo2.fdf_kl = 3;
        skill_over.fdf_kl = 26;
        skill_over.fdf_kh = 34;
        skill_over.fdf_k_EX = 30;
        combo2.df_k_EX = 14;
        skill_over.df_k_EX = 17;
        combo2.df_k1 = 11;
        skill_over.df_k1 = 16;
        combo2.df_k2 = 10;
        skill_over.df_k2 = 15;
        combo2.df_k3 = 5;
        skill_over.df_k3 = 10;
        combo2.db_k = 16;
        skill_over.db_k = 15;
        combo2.dbdf_p = 14;
        skill_over.dbdf_p = 25;
        skill_over.dbdf_p_max = 39;
        skill_over.dbdf_p_max_EX = 46;
        combo2.dfdf_k = 52;
        skill_over.dfdf_k = 46;
        skill_over.dfdf_k_max = 68;
        combo2.dfdf_k_EX = 26;
        skill_over.dfdf_k_EX = 56;
        skill_over.dfdf_k_EX_max = 59;
        skill_over.df_o = 110;
        skill_over.db_o = 49;
        skill_over.df_o_EX = 108;
        skill_over.db_o_EX = 130;
        beCancled = new Object();
        beCancled.punch = 1;
        beCancled.punch2 = 1;
        beCancled.kick_s1 = 1;
        beCancled.punch_l = 1;
        beCancled.kick = 1;
        beCancled.kick2 = 1;
        beCancled.kick_s1 = 1;
        beCancled.kick_s2 = 1;
        beCancled.kick_l = 1;
        beCancled.f_p = 1;
        beCancled.f_p_EX = 1;
        beCancled.df_p = 1;
        beCancled.squatPunch = 1;
        beCancled.squatPunch_l = 1;
        beCancled.squatKick_l = 1;
        beCancled.jumpSkill_punch = 1;
        notTOcancle = new Object();
        notTOcancle.punch = 1;
        notTOcancle.punch2 = 1;
        notTOcancle.punch_l = 1;
        notTOcancle.kick = 1;
        notTOcancle.kick_l = 1;
        notTOcancle.squatPunch = 1;
        notTOcancle.squatPunch_l = 1;
        notTOcancle.squatKick_l = 1;
        notTOcancle.squatKick = 1;
        notTOcancle.pitch = 1;
        s_cancle = new Object();
        s_cancle.punch_l = {kick_l: 1, squatPunch_l: 1, squatKick_l: 1, punch: 1, kick: 1};
        s_cancle.kick_l = {punch: 1, kick: 1};
        s_cancle.squatPunch_l = {punch_l: 1, kick_l: 1, squatKick_l: 1, punch: 1, kick: 1};
        s_cancle.squatKick_l = {punch_l: 1, kick_l: 1, punch: 1, kick: 1};
    } // End of the function
} // End of Class
