var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var terry_shanzi8 = (function () {
    function terry_shanzi8() {
    }
    terry_shanzi8.addSprite8006 = function (mc, own_role) {
        mc.addFrameScript(mc, [1, terry_shanzi8.frame1, 3, terry_shanzi8.frame3, 5, terry_shanzi8.frame5, 7, terry_shanzi8.frame7, 9, terry_shanzi8.frame9, 21, terry_shanzi8.frame21]);
        return;
    };
    terry_shanzi8.frame1 = function (mc) {
        var hitcheck = Hero_HitCheck_obj.getInstance(mc);
        hitcheck.obj_Vx = 0;
        hitcheck.obj_Vy = 0;
        hitcheck.obj_level = 0;
        hitcheck.hurtBack = "";
        hitcheck.hurtAway = "hurt4";
        hitcheck.flag = 1;
        hitcheck.end_status = "";
        hitcheck.Vx = -18;
        hitcheck.Vy = 20;
        hitcheck.a = 3;
        hitcheck.g = 0;
        hitcheck.freezeTime2 = 0;
        hitcheck.freezeTime = 1;
        hitcheck.slowTime = 0;
        hitcheck.shake = 0;
        hitcheck.d_rate = 0.5;
        hitcheck.isObj = true;
        hitcheck.hitType = "hitFire1";
        hitcheck.hitEff = "";
        hitcheck.hitShinning = false;
        hitcheck.reCheck = true;
        hitcheck.checkTimes = 1;
        hitcheck.hitPos = "";
    };
    terry_shanzi8.frame3 = function (mc) {
        var hitcheck = Hero_HitCheck_obj.getInstance(mc);
        hitcheck.obj_Vx = 0;
        hitcheck.obj_Vy = 0;
        hitcheck.obj_level = 0;
        hitcheck.hurtBack = "";
        hitcheck.hurtAway = "hurt4";
        hitcheck.flag = 1;
        hitcheck.end_status = "";
        hitcheck.Vx = -18;
        hitcheck.Vy = 20;
        hitcheck.a = 3;
        hitcheck.g = 0;
        hitcheck.freezeTime2 = 0;
        hitcheck.freezeTime = 1;
        hitcheck.slowTime = 0;
        hitcheck.shake = 0;
        hitcheck.d_rate = 0.5;
        hitcheck.isObj = true;
        hitcheck.hitType = "hitFire1";
        hitcheck.hitEff = "";
        hitcheck.hitShinning = false;
        hitcheck.reCheck = true;
        hitcheck.checkTimes = 1;
        hitcheck.hitPos = "";
    };
    terry_shanzi8.frame5 = function (mc) {
        var hitcheck = Hero_HitCheck_obj.getInstance(mc);
        hitcheck.obj_Vx = 0;
        hitcheck.obj_Vy = 0;
        hitcheck.obj_level = 0;
        hitcheck.hurtBack = "";
        hitcheck.hurtAway = "hurt4";
        hitcheck.flag = 1;
        hitcheck.end_status = "";
        hitcheck.Vx = -22;
        hitcheck.Vy = 25;
        hitcheck.a = 4;
        hitcheck.g = 0;
        hitcheck.freezeTime2 = 0;
        hitcheck.freezeTime = 1;
        hitcheck.slowTime = 0;
        hitcheck.shake = 0;
        hitcheck.d_rate = 0.5;
        hitcheck.isObj = true;
        hitcheck.hitType = "hitFire1";
        hitcheck.hitEff = "";
        hitcheck.hitShinning = false;
        hitcheck.reCheck = true;
        hitcheck.checkTimes = 1;
        hitcheck.hitPos = "";
    };
    terry_shanzi8.frame7 = function (mc) {
        var hitcheck = Hero_HitCheck_obj.getInstance(mc);
        hitcheck.obj_Vx = 0;
        hitcheck.obj_Vy = 0;
        hitcheck.obj_level = 0;
        hitcheck.hurtBack = "";
        hitcheck.hurtAway = "hurt4";
        hitcheck.flag = 1;
        hitcheck.end_status = "";
        hitcheck.Vx = -25;
        hitcheck.Vy = 28;
        hitcheck.a = 4;
        hitcheck.g = 3;
        hitcheck.freezeTime2 = 0;
        hitcheck.freezeTime = 1;
        hitcheck.slowTime = 0;
        hitcheck.shake = 0;
        hitcheck.d_rate = 0.5;
        hitcheck.isObj = true;
        hitcheck.hitType = "hitFire1";
        hitcheck.hitEff = "";
        hitcheck.hitShinning = false;
        hitcheck.reCheck = true;
        hitcheck.checkTimes = 1;
        hitcheck.hitPos = "";
    };
    terry_shanzi8.frame9 = function (mc) {
        var hitcheck = Hero_HitCheck_obj.getInstance(mc);
        hitcheck.obj_Vx = 0;
        hitcheck.obj_Vy = 0;
        hitcheck.obj_level = 0;
        hitcheck.hurtBack = "";
        hitcheck.hurtAway = "hurt4";
        hitcheck.flag = 1;
        hitcheck.end_status = "";
        hitcheck.Vx = -28;
        hitcheck.Vy = 30;
        hitcheck.a = 5;
        hitcheck.g = 3;
        hitcheck.freezeTime2 = 15;
        hitcheck.freezeTime = 5;
        hitcheck.slowTime = 0;
        hitcheck.shake = 0;
        hitcheck.d_rate = 1.2;
        hitcheck.isObj = true;
        hitcheck.hitType = "hitFire1";
        hitcheck.hitEff = "";
        hitcheck.hitShinning = false;
        hitcheck.reCheck = true;
        hitcheck.checkTimes = 1;
        hitcheck.hitPos = "";
    };
    terry_shanzi8.frame21 = function (mc) {
        mc.stop();
        mc.parent.removeChild(mc);
    };
    return terry_shanzi8;
}());
__reflect(terry_shanzi8.prototype, "terry_shanzi8");
//# sourceMappingURL=terry_shanzi8.js.map