var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var Terry_Combo = (function (_super) {
    __extends(Terry_Combo, _super);
    function Terry_Combo(role) {
        var _this = _super.call(this) || this;
        _this.role = role;
        _this.init();
        return _this;
    }
    Terry_Combo.prototype.init = function () {
        this.combo1 = new Object();
        this.combo1.df_k1 = { kick: "df_k2", kick_l: "df_k2" };
        this.combo1.df_k2 = { kick: "df_k3", kick_l: "df_k3" };
        this.combo1.df_k_EX = { kick: "fdf_kl", kick_l: "fdf_kl" };
        this.combo2 = new Object();
        this.skill_over = new Object();
        this.combo2.punch_l = 3;
        this.skill_over.punch_l = 5;
        this.combo2.punch = 7;
        this.skill_over.punch = 9;
        this.combo2.punch2 = 8;
        this.skill_over.punch2 = 12;
        this.combo2.kick_l = 12;
        this.skill_over.kick_l = 12;
        this.combo2.kick = 10;
        this.skill_over.kick = 14;
        this.combo2.kick2 = 6;
        this.skill_over.kick2 = 13;
        this.combo2.squatPunch = 5;
        this.skill_over.squatPunch = 12;
        this.combo2.squatPunch_l = 3;
        this.skill_over.squatPunch_l = 5;
        this.combo2.squatKick = 8;
        this.skill_over.squatKick = 13;
        this.combo2.squatKick_l = 3;
        this.skill_over.squatKick_l = 5;
        this.combo2.heavyHit = 12;
        this.skill_over.heavyHit = 15;
        this.combo2.f_p = 9;
        this.skill_over.f_p = 13;
        this.combo2.f_p_EX = 8;
        this.skill_over.f_p_EX = 10;
        this.combo2.df_p = 4;
        this.skill_over.df_p = 9;
        this.combo2.bdf_k = 24;
        this.skill_over.bdf_k = 30;
        this.combo2.df_ph = 14;
        this.skill_over.df_ph = 32;
        this.combo2.df_pl = 15;
        this.skill_over.df_pl = 23;
        this.combo2.df_p_EX = 17;
        this.skill_over.df_p_EX = 32;
        this.skill_over.db_k = 18;
        this.combo2.fdb_p_EX = 16;
        this.skill_over.fdb_p_EX = 21;
        this.combo2.db_p = 28;
        this.skill_over.db_p = 28;
        this.combo2.fdf_p = 4;
        this.skill_over.fdf_p = 24;
        this.combo2.fdf_p_EX = 17;
        this.skill_over.fdf_p_EX = 29;
        this.combo2.fdf_kl = 3;
        this.skill_over.fdf_kl = 26;
        this.skill_over.fdf_kh = 34;
        this.skill_over.fdf_k_EX = 30;
        this.combo2.df_k_EX = 14;
        this.skill_over.df_k_EX = 17;
        this.combo2.df_k1 = 11;
        this.skill_over.df_k1 = 16;
        this.combo2.df_k2 = 10;
        this.skill_over.df_k2 = 15;
        this.combo2.df_k3 = 5;
        this.skill_over.df_k3 = 10;
        this.combo2.db_k = 16;
        this.skill_over.db_k = 15;
        this.combo2.dbdf_p = 14;
        this.skill_over.dbdf_p = 25;
        this.skill_over.dbdf_p_max = 39;
        this.skill_over.dbdf_p_max_EX = 46;
        this.combo2.dfdf_k = 52;
        this.skill_over.dfdf_k = 46;
        this.skill_over.dfdf_k_max = 68;
        this.combo2.dfdf_k_EX = 26;
        this.skill_over.dfdf_k_EX = 56;
        this.skill_over.dfdf_k_EX_max = 59;
        this.skill_over.df_o = 110;
        this.skill_over.db_o = 49;
        this.skill_over.df_o_EX = 108;
        this.skill_over.db_o_EX = 130;
        this.beCancled = new Object();
        this.beCancled.punch = 1;
        this.beCancled.punch2 = 1;
        this.beCancled.kick_s1 = 1;
        this.beCancled.punch_l = 1;
        this.beCancled.kick = 1;
        this.beCancled.kick2 = 1;
        this.beCancled.kick_s1 = 1;
        this.beCancled.kick_s2 = 1;
        this.beCancled.kick_l = 1;
        this.beCancled.f_p = 1;
        this.beCancled.f_p_EX = 1;
        this.beCancled.df_p = 1;
        this.beCancled.squatPunch = 1;
        this.beCancled.squatPunch_l = 1;
        this.beCancled.squatKick_l = 1;
        this.beCancled.jumpSkill_punch = 1;
        this.notTOcancle = new Object();
        this.notTOcancle.punch = 1;
        this.notTOcancle.punch2 = 1;
        this.notTOcancle.punch_l = 1;
        this.notTOcancle.kick = 1;
        this.notTOcancle.kick_l = 1;
        this.notTOcancle.squatPunch = 1;
        this.notTOcancle.squatPunch_l = 1;
        this.notTOcancle.squatKick_l = 1;
        this.notTOcancle.squatKick = 1;
        this.notTOcancle.pitch = 1;
        this.s_cancle = new Object();
        this.s_cancle.punch_l = { kick_l: 1, squatPunch_l: 1, squatKick_l: 1, punch: 1, kick: 1 };
        this.s_cancle.kick_l = { punch: 1, kick: 1 };
        this.s_cancle.squatPunch_l = { punch_l: 1, kick_l: 1, squatKick_l: 1, punch: 1, kick: 1 };
        this.s_cancle.squatKick_l = { punch_l: 1, kick_l: 1, punch: 1, kick: 1 };
    };
    return Terry_Combo;
}(Combo_listener));
__reflect(Terry_Combo.prototype, "Terry_Combo");
//# sourceMappingURL=Terry_Combo.js.map