class misson_conf
{
	public static xml = '<mession>                                                                                                                       '
+ '	<design comicType="0" gameMode="0">                                                                                            '
+ '		<stage fighter="naruto,rukia,sasuke" assister="kon" map="muyecun" />                                                        '
+ '		<stage fighter="sasuke_xz,naruto,rukia" assister="tenten" map="senlin" />                                                          '
+ '		<stage fighter="gaara,temari,killerbee" assister="ino" map="louding" />                                                      '
+ '		<stage fighter="sasuke_xz,karin,juggo" assister="suigetsu" map="pubu" />                                                     '
+ '		<stage fighter="itachi" assister="itachi" map="yuzhibocun" attackRate="2" hpRate="2" />                                      '
+ '		<stage fighter="naruto_xianren,jiraiya,orochimaru" assister="tsunate" map="wenquan" />                                       '
+ '		<stage fighter="pain,konan" assister="madara" map="wuyingcun" attackRate="1.2" hpRate="1.2" />                               '
+ '		<stage fighter="obito_s2" assister="madara" map="senlin" attackRate="1.5" hpRate="2" />                                      '
+ '	</design>                                                                                                                      '
+ '	                                                                                                                               '
+ '	<design comicType="0" gameMode="1">                                                                                            '
+ '		<stage fighter="naruto,rukia,sasuke" assister="kon" map="muyecun" />                                                        '
+ '		<stage fighter="sasuke_xz,naruto,rukia" assister="tenten" map="senlin" />                                                          '
+ '		<stage fighter="gaara,temari,killerbee" assister="ino" map="louding" />                                                      '
+ '		<stage fighter="sasuke_xz,karin,juggo" assister="suigetsu" map="pubu" />                                                     '
+ '		<stage fighter="itachi" assister="itachi" map="yuzhibocun" />                                                                '
+ '		<stage fighter="naruto_xianren,jiraiya,orochimaru" assister="tsunate" map="wenquan" />                                       '
+ '		<stage fighter="pain,konan" assister="madara" map="wuyingcun" />                                                             '
+ '		<stage fighter="obito_s2" assister="madara" map="senlin" />                                                                  '
+ '	</design>                                                                                                                      '
+ '	                                                                                                                               '
+ '	<design comicType="1" gameMode="0">                                                                                            '
+ '		<stage fighter="orihime,chad,ichigo" assister="kon" map="muyecun" />                                                '
+ '		<stage fighter="naruto,rukia,sasuke_xz" assister="kon" map="muyecun" />                                                          '
+ '		<stage fighter="ichigo_wanjie,rukia_shijie,byakuya" assister="uryuu" map="liuhunjie" />                                      '
+ '		<stage fighter="kenpachi,ikkaku,toushirou" assister="yachiru" map="zoulang" />                                               '
+ '		<stage fighter="ichigo_xuhua" assister="orihime" map="shihunjietongdao" attackRate="1.5" hpRate="1.5" />                     '
+ '		<stage fighter="toushirou_wanjie,byakuya_wanjie,mayuri" assister="kenpachi" map="shuangji" />                                '
+ '		<stage fighter="ulquiorra,yin" assister="grimmjow" map="jingyantin" attackRate="1.2" hpRate="1.2" />                         '
+ '		<stage fighter="aizen" assister="stake" map="shuangji" attackRate="1.5" hpRate="2" />                                        '
+ '	</design>                                                                                                                      '
+ '	                                                                                                                               '
+ '	<design comicType="1" gameMode="1">                                                                                            '
+ '		<stage fighter="naruto,chad,ichigo" assister="kon" map="muyecun" />                                                '
+ '		<stage fighter="naruto,rukia,sasuke_xz" assister="kon" map="muyecun" />                                                          '
+ '		<stage fighter="ichigo_wanjie,rukia_shijie,byakuya" assister="uryuu" map="liuhunjie" />                                      '
+ '		<stage fighter="kenpachi,ikkaku,toushirou" assister="yachiru" map="zoulang" />                                               '
+ '		<stage fighter="ichigo_xuhua" assister="orihime" map="shihunjietongdao" />                                                   '
+ '		<stage fighter="toushirou_wanjie,byakuya_wanjie,mayuri" assister="kenpachi" map="shuangji" />                                '
+ '		<stage fighter="ulquiorra,yin" assister="grimmjow" map="jingyantin" />                                                       '
+ '		<stage fighter="aizen" assister="stake" map="shuangji" />                                                                    '
+ '	</design>                                                                                                                      '
+ '	                                                                                                                               '
+ '</mession>                                                                                                                      ';
	
};

